---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - batch.my.domain.com
  resources:
  - scaler
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.my.domain.com
  resources:
  - scaler/finalizers
  verbs:
  - update
- apiGroups:
  - batch.my.domain.com
  resources:
  - scaler/status
  verbs:
  - get
  - patch
  - update
