# permissions for end users to edit secretcreators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretcreator-editor-role
rules:
- apiGroups:
  - secretcreator.example.com
  resources:
  - secretcreators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secretcreator.example.com
  resources:
  - secretcreators/status
  verbs:
  - get
