# permissions for end users to view secretcreators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretcreator-viewer-role
rules:
- apiGroups:
  - secretcreator.example.com
  resources:
  - secretcreators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - secretcreator.example.com
  resources:
  - secretcreators/status
  verbs:
  - get
