# permissions for end users to edit customscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: customscaler-editor-role
rules:
- apiGroups:
  - batch.domain.example.com
  resources:
  - customscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.domain.example.com
  resources:
  - customscalers/status
  verbs:
  - get
