# permissions for end users to view customscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: customscaler-viewer-role
rules:
- apiGroups:
  - batch.domain.example.com
  resources:
  - customscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.domain.example.com
  resources:
  - customscalers/status
  verbs:
  - get
