---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - batch.domain.example.com
  resources:
  - customscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.domain.example.com
  resources:
  - customscalers/finalizers
  verbs:
  - update
- apiGroups:
  - batch.domain.example.com
  resources:
  - customscalers/status
  verbs:
  - get
  - patch
  - update
