apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: assignment
  name: assignment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assignment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: assignment
    spec:
      containers:
      - image: vinit747/dev1:v3
        name: dev1
        resources: {}
status: {}
