---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-db-velotio-com-v1-mongodb
  failurePolicy: Fail
  name: mmongodb.kb.io
  rules:
  - apiGroups:
    - db.velotio.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - mongodbs
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-db-velotio-com-v1-mongodb
  failurePolicy: Fail
  name: vmongodb.kb.io
  rules:
  - apiGroups:
    - db.velotio.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - mongodbs
  sideEffects: None
