---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - batch.my.example.com
  resources:
  - multilevels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.my.example.com
  resources:
  - multilevels/finalizers
  verbs:
  - update
- apiGroups:
  - batch.my.example.com
  resources:
  - multilevels/status
  verbs:
  - get
  - patch
  - update
