kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: pod-reader
rules:
- apiGroups: ["*"] # "" is core API group
  resources: ["services", "pods", "deployments"]
  verbs: ["create", "update", "patch", "get", "watch", "list", "delete"]