apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: proxy-role
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: k8s-dev-training
    app.kubernetes.io/part-of: k8s-dev-training
    app.kubernetes.io/managed-by: kustomize
  name: proxy-role
rules:
- apiGroups:
  - "apps"
  resources:
  - "deployments"
  verbs:
  - create
  - list
  - get
  - watch
  - update
  - delete
- apiGroups:
  - "batch"
  resources:
  - "jobs"
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
