# permissions for end users to edit demovolumes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: demovolume-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-assignment2
    app.kubernetes.io/part-of: k8s-assignment2
    app.kubernetes.io/managed-by: kustomize
  name: demovolume-editor-role
rules:
- apiGroups:
  - demo.domo.civo.io
  resources:
  - demovolumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.domo.civo.io
  resources:
  - demovolumes/status
  verbs:
  - get
