# permissions for end users to edit procos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: procos-editor-role
rules:
- apiGroups:
  - batch.my.domain
  resources:
  - procos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.my.domain
  resources:
  - procos/status
  verbs:
  - get
