
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - velotio.pankaj.io
  resources:
  - myjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - velotio.pankaj.io
  resources:
  - myjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - velotiov1
  resources:
  - cronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - velotiov1
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
