# permissions for end users to edit customdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: customdeployment-editor-role
rules:
- apiGroups:
  - custdep.paravkaushal.dev
  resources:
  - customdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - custdep.paravkaushal.dev
  resources:
  - customdeployments/status
  verbs:
  - get
