---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - custdep.paravkaushal.dev
  resources:
  - customdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - custdep.paravkaushal.dev
  resources:
  - customdeployments/finalizers
  verbs:
  - update
- apiGroups:
  - custdep.paravkaushal.dev
  resources:
  - customdeployments/status
  verbs:
  - get
  - patch
  - update
