apiVersion: apps/v1
kind: Deployment
metadata: 
  name: demo-deployment
  namespace: pankaj
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: web
          image: nginx:1.12
          ports:
            - containerPort: 80