apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: pankaj
  name: demo-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]