# permissions for end users to view myresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: myresource-viewer-role
rules:
- apiGroups:
  - util.my.domain
  resources:
  - myresources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - util.my.domain
  resources:
  - myresources/status
  verbs:
  - get
