
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - util.my.domain
  resources:
  - myresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - util.my.domain
  resources:
  - myresources/finalizers
  verbs:
  - update
- apiGroups:
  - util.my.domain
  resources:
  - myresources/status
  verbs:
  - get
  - patch
  - update
